var plain = [
"the crowd go back",
"but when people doubt him",
"you know that we rock",
"so if it's true",
"you wanna see the fight",
"you wanna hear some more",
"if somebody gets dumb",
"burn with the tempo",
"but when people think",
"so if it's dope",
"now i'm back",
"too damn hype",
"you should just stop",
"you try to escape",
"don't stop my show",
"every single dime",
"i'm like the fresh prince",
"now pump it up",
"the moral of the story",
"i'm like that sound",
"the rhyme is too strong",
"too damn hype",
"too damn tight",
"too many doubters",
"you know i love rap",
"the crowd gets bitten",
"you wanna play hardball",
"the party was jammin",
"the rhyme is all burnt",
"too far i guess",
"you'd see who it was",
"so pump that stuff",
"now there's six",
"nintendo in the place",
"you wanna battle",
"battle started",
"my crew is all alone",
"i metamorphosise",
"you know that we're def",
"i'm not dissin but",
"too far up",
"not only one reason",
"i'm like an oven",
"one day i was rappin",
"one day i went outside",
"one day i was arrested",
"one day i went bezerk",
"one day i thought",
"one day i got dressed",
"once upon a time",
"I'm fred flintstone",
"we just rock",
"we just buggin",
"we wanna dance everyday",
"we slap you",
"she says baby",
"i'm that stuff like this",
"you could never be large",
"the party is over",
"he doesn't matter",
"now bring the beat",
"now bring the crowd",
"we work hard to rock",
"a little somethin' somethin'",
"the dj cuts suckers",
"the rhyme explodes",
"it goes black",
"a rhythmic train line",
"i'm the man",
"i'm the ignition",
"daddio wants you",
"wednesday october",
"kickin it down",
"japan wants you",
"brooklyn dynamite",
"spinnin and clappin",
"that was cool",
"you wanna panic",
"i said hey yo",
"you should think twice",
"he does donkey kong",
"i like to rock",
"i like to tease",
"i like to think",
"i like to say",
"i like to spend",
"i love to plea",
"i love to make love",
"i'm reigning king",
"i'm a subtle mix",
"i'm wonderin why",
"i walked in the club",
"i walked upstairs",
"i went inside",
"i went back to school",
"we're jumpin and spinnin",
"we're waving at home",
"we're standin outside",
"we're seriously dope",
"we're wreckin that hangout",
"we're hungry always",
"we're experienced",
"we're decaptitated",
"we're stepping to you",
"we're not into geography",
"we're sheila's head",
"i'm entirely smooth",
"i'm smoother than that",
"i'm looking around",
"Briefcase of ryhmes",
"quincy jones airport",
"kissing and hugging ai",
"swimming in philly",
"chaos throughout",
"guts always gold",
"homes for the literary",
"1989",
"hustling, sliding, grabbing",
"word yo",
"hesitation popped",
"midnight biking",
"Sniffing daisies",
"sherlock holmes workin",
"stolen from school",
"satin bed sheets",
"cop pulled out his gun",
"amnesia now i'm back",
"i'm grounded for years",
"i'm trapped on the radio",
"i'm strong like the doctor",
"i'm inclined to rhyme",
"i'm almost clappin",
"i'm strapped with nines",
"i'm in your car",
"i'm not a troublemaker",
"i'm like the movies",
"i can't forget it",
"i increased my crew",
"my crew is dead",
"my crew is right",
"my crew is compulsive",
"my crew is slow",
"my rhyming is wack",
"rhymes have been written",
"my rhymes take heed",
"my rhyming is weak",
"rhyming is tequila",
"my rhyming is cooling",
"my rhymes are dope",
"my rhymes areobics",
"my rhymes need lungs",
"my rhymes take care",
"I cause pasazz",
]

var adjectives = [
"this rhyme is real XXX",
"the prince is XXX",
"but now I'm XXX",
"so damn XXX",
"but now I'm XXX",
"it's really XXX",
"too damn XXX",
"my crew is XXX",
"my friends are XXX",
"your rhyming is XXX",
"he was XXX",
"she turned XXX",
"the party was XXX",
"battle turned XXX",
"cool like XXX",
"fresh like XXX",
"sex is XXX",
"hoes were XXX",
"my mom is XXX",
"our music is XXX",
"the fuse is XXX",
"parties are XXX",
"your perfume smells XXX",
"your radio is XXX",
]

var verbs = [
"you can't XXX",
"but I always XXX",
"we gon XXX",
"freestyle and XXX",
"somebody should XXX",
"my crew is XXX",
"my crew isn't XXX",
"your radio is XXX",
]

var nouns = [
"the crowd screams XXX",
"DJ hollerin XXX",
"you may like XXX",
"burn the XXX",
"i refuse XXX",
"my crew liking XXX",
"my friends tried XXX",
"interrogate XXX",
"samurai XXX",
"killing the XXX",
"driving to get a XXX",
"blind to the XXX",
"females aren't XXX",
"banging on the XXX",
"caressing the XXX",
"my car is a XXX",
"because of the XXX",
"frontin it on the XXX",
"I got the XXX",
"we be the XXX",
"but girls ain't XXX",
"she had this XXX",
"friends cause XXX",
"I'm like a XXX",
"so pump up the XXX",
"too late for XXX",
"he gave me a XXX",
"she wasn't a XXX",
"you know my XXX",
"lethal like XXX",
"just like a XXX",
"i'm just a XXX",
"shockin like a XXX",
"needless XXX",
"so i said XXX",
"captain of the XXX",
"now there's a XXX",
"slaying your XXX",
"horns on the XXX",
"givin it a XXX",
"history of a XXX",
"mixin in a XXX",
"dinner was XXX",
"ski on the XXX",
"now i'm the XXX",
"this kinda XXX",
"mount olympus XXX",
"wreckin in the XXX",
"keeping my XXX",
"summoned up the XXX",
"heed my XXX",
"ribs and XXX",
"but snap my XXX",
"shootin the XXX",
"talkin to the XXX",
"pretend to be the XXX",
"water on the XXX",
"butcher the XXX",
"driving off the XXX",
"wicky wack XXX",
"too much XXX",
"standing in the XXX",
"flippin through the XXX",
"hardcore XXX",
"ultimate XXX",
"michelle the XXX",
"beginning the XXX",
"eighteenth XXX",
"coffee and XXX",
"mama was a XXX",
"killed my XXX",
"fantasy XXX",
"reverend XXX",
"something like XXX",
"release my XXX",
"chitlins and XXX",
"status was XXX",
"fightin the XXX",
"lovin my XXX",
"upset the XXX",
"flintstone XXX",
"tell'em the XXX",
"raise the XXX",
"money like XXX",
"order in some XXX",
"nobody's the XXX",
"look like XXX",
"working on XXX",
"42nd street XXX",
"fatal XXX",
"jungle XXX",
"hallway XXX",
"nintendo XXX",
"mistook the XXX",
"posse on XXX",
];